services:
  - type: web
    name: strapi-demo-api
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 12.18.4
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-demo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
    autoDeploy: false
  - type: web
    name: strapi-demo-web
    env: static
    buildCommand: cd web && yarn && yarn build
    staticPublishPath: ./web/public
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: STRAPI_API_HOST
        fromService:
          name: strapi-demo-api
          type: web
          property: host
    routes:
    - type: rewrite
      source: /api/*
      destination: https://strapi-demo-api.onrender.com/*
    autoDeploy: false

databases:
  - name: strapi-demo-db
    plan: starter
